# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0b5f21b168dbe8df4672de94f0de9d41f3d90b30c9ff3b012db82c2087369e248802c3b900a4c3cb7cc45be1af4c5699b4995ee7c5c0518afc7623e84f646ca

test:
  secret_key_base: c75d998a8532db28a8a17422f367f3634aab341e19d9a28381d7367f30fca769d1a43dee56b25dc6313a4d52f5969f294ce26d0e30097ae1d38679013392b3a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
